const router=require("express").Router();
const {Register,Login,RegisterCourse,DropCourse}=require("../controller/student");
const RegisterValidation=require("../middleware/RegisterValidation");
const LoginValidation=require("../middleware/LoginValidation");
const RegisterCourseValidation=require("../middleware/RegisterCourseValidation");
const  RegisterCourseEmailValidation=require("../middleware/RegisterCourseEmailValidation");
router.post('/register',RegisterValidation,Register);
router.post('/login',LoginValidation,Login);
router.post('/registercourse/:email', RegisterCourseEmailValidation,RegisterCourseValidation,RegisterCourse);
router.post('/dropcourse/:email', DropCourse);
module.exports=router;